#!/bin/bash

set -e

# Deploy tar-files and checksums to the firehol website

if [ ! -f /tmp/ssh-key-loaded ]
then
  echo "No ssh key decrypted - skipping deployment to website"
  exit 0
fi

case "$TRAVIS_BRANCH" in
  master|stable-*)
    :
  ;;
  *)
    echo "Not on master or stable-* branch - skipping deployment to website"
    exit 0
  ;;
esac

if [ "$TRAVIS_PULL_REQUEST" = "true" ]
then
  echo "Building pull request - skipping deployment to website"
  exit 0
fi

if [ "$TRAVIS_TAG" != "" ]
then
  echo "Building tag - skipping deployment to website"
  exit 0
fi

ssh-keyscan -H firehol.org >> ~/.ssh/known_hosts
ssh travis@firehol.org mkdir -p website/$TRAVIS_BRANCH/
rsync -a $TRAVIS_BRANCH $TRAVIS_BRANCH.conf travis@firehol.org:website/$TRAVIS_BRANCH
ssh travis@firehol.org touch website/$TRAVIS_BRANCH/complete.txt
echo "Visit https://firehol.org/travis-project.log check deployment"
